### ISSUE TITLE
Add links to Ngame's album premiere stream recordings

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#103]
Ngame heroically reuploaded many album streams to their youtube channel, which should be linked to as wiki commentary:
- Ancestral
- Cosmic Caretakers
- Moons of Theseus
- Songs for Rune (not yet on wiki)
- Oceanfalls Vol. 1
- Strife 2
- many canwc albums (already done for existing albums on the wiki)

https://www.youtube.com/@Ngame989/videos

**Comment by towerofnix** [comment]
I think this makes more sense to do as part of the next release instead of post-release, tying in with other similar-across-multiple-album refinements & new additions (vs. fixes to existing data/content), but feel free to veto my opinion if you disagree!
