### ISSUE TITLE
Expand Additional Files

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#105]
Most HSGaiden/UMSPAF/CaNMT albums have additional content in the form of commentary booklets and other fun things that aren't on the wiki right now. Also, should check other fandom/beyond albums for such files to potentially add (Team Paradox has a commentary booklet for instance). We should be wary about paid-only albums but free download albums or abandonware should be fair game, right?

UMSPAF
--
- [x] SBURB OST
  - audio commentary (80MB / 100MB)
  - booklet (48MB)
  - Build Theme (Swag Gate) ft. VeritasUnae 
- [x] LoFaM2
  - lofam2_artwork.zip (49MB) (includes some bonus pieces)
  - booklet (47MB)
- [x] LoFaM3
  - lofam3_artwork.zip (28MB) (just track art)
  - booklet (40MB)
  - Garden of Eden - Full Version + sheet music
  - sord... NEWF AND IMPROVD
  - Disc 2 wallpapers
  - 'Fixed' commentary booklet (missing)
- [x] Beforus
  - Beforus Track Art.zip (appears to be just track art)
  - booklet (85MB)
- [x] Bee-forus Seatbelt Safebee
  - Seatbelt Safebee track art.zip (includes some alt covers and a bigger version of the banner!)
  - booklet (see #102)
- [x] Weird Puzzle Tunes (Art of the Project - WPT.zip) (includes one piece of bonus art)
- [x] Ancestral
  - Ancestral Art.rar (appears to be just track art)
  - booklet (35MB)
- [x] LoFaM4
  - Lofam 4 Art.rar (includes bonus artwork totalling ~20MB)
  - booklet (54MB)
- [x] Xenoplanetarium
  - booklet (17MB)
- [x] Gristmas Carols (booklet)
- [x] Cosmic Caretakers (booklet)
- [x] Moons of Theseus (booklet) (13MB)
- [x] Friendsymphony (additional_credits.txt) (see #107)
- [x] LoFaM5
  - booklet (28MB)

Other Fandom
--
- [x] LoFaM (booklet + original version of wiki banner)
- [x] Jailbreak Vol. 1 (Bars / Logorg / Drillgorg / Retrobution .nsf files + about txt)
- [x] cool and new volume 2/II
  - booklets (see #102)
- [x] Cool and new Volume V (booklet) (26MB)
- [x] Team Paradox (booklet)
- [x] The Baby is You (lyrics for queer dicks.txt)

Paid Albums (do not add additional files)
--
-  P[S] (booklet) (see #107)
-  Ithaca
    - credits.jpg
    - photo_1 and photo_2.jpg
- Comfortable Bugs (credits_page.jpg)
- Hush
    - _details.txt (lyrics)
    - _01, _02, and _03.jpg
- Someday (5 wallpapers)
- Slender: The Arrival Soundtrack (alternate cover from Steam download)
- Triassic Slump (commentary of some sort)

Unable to verify presence of additional files:
--
Ulterior Motives, After-Party Animal, Dare, A Nameless Inheritance, The Consuming Shadow, ✌︎❒︎♏︎ ⍓︎□︎◆︎ ●︎□︎⬧︎⧫︎✍︎, entertaining sound, WHAT, Bashful Hearts Out, CLASS ACT, all Secily Iopara, all UNDERTALE & DELTARUNE. Note these are all paid albums anyways.

**Comment by towerofnix** [comment]
Yep, all freely-available additional files should be added to the wiki (not ruling out exceptional cases! but can't think of any, yet).

I'm adding this to the next release milestone because it's closely related to other refinements to existing albums on the wiki including full-resolution artworks.
