### ISSUE TITLE
Add P[S]/Friendsymphony booklet commentary

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#107]
Well in Friendsymphony's case it's just a text file but you get the point.

**Comment by Niklink** [comment]
I seem to have failed to notice this note by @towerofnix:

> please support the group by purchasing the album - it comes with a commentary booklet i don't intend to transcribe here.

Any current thoughts? It's been two and a half years since then, does this still stand?

**Comment by towerofnix** [comment]
P[S]'s commentary booklet is more personal than most album booklets. As long as the album is available for purchase, I don't think it should be put freely online (by anyone besides the authors) - and if the album is taken down we should reach out to the artists before sharing.
