### ISSUE TITLE
Shortcuts missing Audio Commentary bonus track

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#110]
Shortcuts has a bonus track missing on the wiki, named `Audio Commentary Featuring David Ellis, Robert J! Lake, Yishan Mai, Marcy Nabors and Corbin Pangilinan`. It's them talking about the album while it plays. Usually the proper procedure would be to transcribe everything they say as 'lyrics'. But it's also proper procedure to not include bonus content for paid albums directly. Seeing as the entirety of the audio commentary mainly relies on what is being said, to transcribe it would be like 99% of the way to pirating it. But unlike commentary booklets, this is technically part of the tracklist itself, as track 8, and thus constitutes part of the album structure. So I think we should add it to the track list and add an editor's note explaining the lack of transcription. Which saves us an assload of work for the time being, too, so that's nice.

**Comment by towerofnix** [comment]
If the artists are all OK with sharing bonus files (which we can check on some other time), I'm self-assigning the actual transcription part, take a break bro
