### ISSUE TITLE
Album additions: Oceanfalls Vol. 4, Oceanfables: Ray of Light, Oceanfalls Vol. 5

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#112]
These dropped without me even noticing! I haven't listened to Oceanfables yet but Vol. 4 owns.

- [{ Oceanfalls } Vol. 4](https://nightslights.bandcamp.com/album/oceanfalls-vol-4) (January 25, 2023)
- [Oceanfables: Ray of Light](https://nightslights.bandcamp.com/album/oceanfables-ray-of-light) (March 18, 2022)

**Comment by towerofnix** [comment]
Putting this to next release, potentially alongside Vast Error + some other stuff!

**Comment by Niklink** [comment]
Resolved by #220.
