### ISSUE TITLE
Carefree Consternation (FriendSymphony) has... BEES

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#128]
🐝 

&nbsp;

Bees.
&nbsp;
&nbsp;

&nbsp;&nbsp;🐝 

&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🐝

**Comment by Niklink** [comment]
Also `Beetermination (Thinking Bee)`.
