### ISSUE TITLE
✌​︎​❒​︎​♏​︎ ⍓​︎​□​︎​◆​︎ ●​︎​□​︎​⬧​︎​⧫​︎​✍ (Are You Lost?) missing 2 unknown bonus tracks

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#143]
Bandcamp embed info lists it as having 9 tracks, not 7.

@towerofnix maybe you know something about this...?

edit: one of them is [UNRESPONSIVE, REDACTED (Gaster's Theme Remix)](https://www.youtube.com/watch?v=OWJz1s2iLLg)

**Comment by towerofnix** [comment]
I...didn't actually buy this album... I only listened to it on Bandcamp, sorry.... :P

It's obviously worth a few dollars though, I'll get back to you with the track details!
