### ISSUE TITLE
Additional file (mini SWF) for Sburban Rush (LOFAM)

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#183]
The commentary discusses an animation that the artist made which went along with their song for the fanventure they were doing, and [we have that flash file](https://cdn.discordapp.com/attachments/779895315750715422/1101570969753112626/the_straggler___sburban_rush_by_ralengainsborough_d2uun8t.swf)! It should be included as an additional file.

Thanks, Makin!

**Comment by Niklink** [comment]
Resolved by #220.
