### ISSUE TITLE
"Black Hole's Dozen" (lofam5) references g'nite cutie

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#209]
That's what I'm calling it but you can call it something different. 🎁 

https://fwugradiation.tumblr.com/post/25311896891/fwugradiation-did-something-cute-with-uus

From Monckat:

> something i just remembered- my track Black Hole's Dozen from lofam5 quotes the lyrist and the thirteenth hour, but also the outro quotes this specific arrangement of the thirteenth hour: https://fwugradiation.tumblr.com/post/25311896891/fwugradiation-did-something-cute-with-uus
>
> in the lofam5 commentary i lumped it in with the thirteenth hour because this version doesn't have a name of its own, but i wonder if this should get a mention on the wiki

Also from Makin, check the disk tracks:

> isn't this also what's quoted in one of the disk 1/2 things?

**Comment by Niklink** [comment]
It's called 'The Thirteenth Troll' in the sound test (I wasn't responsible for adding it)
