### ISSUE TITLE
Album addition: Cristata - CYBER CITY SOUND PAK

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#214]
Ten tracks (plus one) of Deltarune, Undertale, and maybe even Homestuck electronic extravaganza! Excitement! (I can't believe it's been almost three years since the last album, actually kinda shocking.)

Featured tracks are credited in each track's info, super sweet.

> HEY⠀⠀ !!! 3VER WANNA [take a ride] AROUND [[insert zipcode here]] BLAST1NG THE COOL, SWEET SOUNDS FROM THE DARK? BUT YOU CANT? BEC4USE YOURE A [$#!&ing] L1ght< ner?! WELL YOUR OLD PAL ⠀⠀⠀ !SPAMTON HAS THE BEST DEAL YOU'LL EVER [look , its over there!] ON!!!
>
> FOR ONLY 7.99 OF YOUR PATHET1C [[wacky stacks]] YOU CAN GET THIS [[specil disk and mp3 and wav and]] THAT COMES WITH NOT [one] NOT [duo] BUT ten EXCLUSIVE SONGS I [[promise?]] YOU CANT FIND ANYWHERE EL SE! 4ND MABY A B0NUS 2... . . . . ..//?[
>
> NOW Y OU 2 CAN [[pissing off]] THOSE STUP 1D N3IGHBORS AT [sale ends 4 am est] BECAUSE YOU CANT STOP [limited edition party juice flavor]!
>
> THIS IS [limited time deal, act fast!] SO DONT [$@#$ing] W41T
>
> CYBER CITY SOUND PAK! TELL YOUR [[friends and family sale going on now!]]
>
> BUY NOW >>[[hyperlink blocked]]<<
>
> [[hyperlink blocked]]
>
> [[hyperlink blocked]]
>
> [[hyperlink blocked]]

**Comment by towerofnix** [comment]
Commentary from Twitter, too:

> Hi I'm Goomy! I've got a #DELTARUNE remix album coming out this friday, it'll be available on my Youtube and Bandcamp. If you've heard the BIG SHOT (1997) remix... There's gonna be more of that!
>
> I've been working on this since Chapter 2 dropped, and I'm so excited to finally release this to you all. This album means a whole lot to me and I'd love for you all to share around it if you like it too.

**Comment by Niklink** [comment]
Resolved by #220.
