### ISSUE TITLE
Improve Vol. 7 site banner

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#225]
Figured out how to extend it horizontally. Only took me three years because im idiot

Old:
![banner-1](https://github.com/hsmusic/hsmusic-data/assets/25875275/64271c4c-db95-4fb3-82dc-f9d04d8f2275)

New:
![image](https://github.com/hsmusic/hsmusic-data/assets/25875275/092f96f5-d201-4bcd-9d95-ec4188c318f0)

**Comment by towerofnix** [comment]
Is this AI /s

**Comment by Niklink** [comment]
turns out that on the album cover you can see the entirety of rose's silhouette, which gets cut off in the homestuck panel it's taken from. so i blew it up and used it as a reference point

**Comment by towerofnix** [comment]
'Kay that's pretty great.
