### ISSUE TITLE
Additional Perfectly Generic Album missing references

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#229]
Following up to #228, I went over the whole album looking for other missing references. In summary:

* **New and Improved:**
  * Missing Penumbra Phantasm (throughout song)
* **Gaster's Theme:**
  * Missing MEGALOVANIA / Megalovania (2:36), at bottom of list
* **Another Noir (Extended Void Mix):**
  * ~~Missing Black (1:10, 2:15) for its piano parts, before Liquid Negrocity~~
  * Missing Amen, Brother (0:27 probably, 3:56 definitely), sample
* **Welcome to Your New Suburban Reality:**
  * Missing Sburban Jungle (0:00–0:18 and 4:46)
* **Eternally You:**
  * ~~0:00–0:18 is backwards, should reverse this and check for a motif here just in case.~~
  * Missing Flare (0:24), as mentioned by EzzyCrafts
  * Missing Homestuck Anthem (3:15, 4:24)

Full details with many more timestamps [in #references-project](https://discord.com/channels/749042497610842152/749059442523504728/1139403916832948246).

**Comment by Niklink** [comment]
reversing eternally you's intro has basically no effect, nothing there
