### ISSUE TITLE
DK Rap missing some artist/contributor info

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#249]
- George Andreas (lyrics)
- George Andreas, Chris Sutherland (vocals)
- Gregg Mayles, Steve Mayles, Ed Bryan, and Chris Peil (chorus)
- D.K., Donkey Kong! (leader of the bunch; you know him well)

remember to clean up lyrics commas

**Comment by towerofnix** [comment]
<img width="391" alt="Development: Successfully merging a pull request may close this issue. (is a merged pull request)" src="https://github.com/hsmusic/hsmusic-data/assets/9948030/9f54e1d4-6741-4775-8042-d07c17f728e9">

well, it did say "may"
