### ISSUE TITLE
Album additions: Highblood!

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#332]
Highblood, AKA Xszelor Azearelth, is self-described as a "death/grind one man band, based on Homestuck highblood purple caste lyric theme." It's totally grindcore and totally Homestuck. There's quite a bit here!

- [x] [Demo 2019-2021 (Vicious Valor)](https://thehighblood.bandcamp.com/album/demo-2019-2021-vicious-valor), 4 tracks
- [x] [Army of the wicked God](https://thehighblood.bandcamp.com/album/army-of-the-wicked-god), single
- [x] [Remains of formed pain](https://thehighblood.bandcamp.com/album/remains-of-formed-pain), single
- [x] [Grim chain of feast](https://thehighblood.bandcamp.com/album/grim-chain-of-feast), 9 tracks, their debut album
- [x] [War Marks](https://thehighblood.bandcamp.com/album/war-marks), 4 album EP
- [x] [Legion](https://thehighblood.bandcamp.com/album/legion), single
- [x] [Rites of Bloodgrinded](https://thehighblood.bandcamp.com/album/rites-of-bloodgrinded), 12 tracks
- [x] [His Honorable Tyrrany](https://thehighblood.bandcamp.com/album/his-honorable-tyranny), single
- [x] [Genesis Genocide](https://thehighblood.bandcamp.com/album/genesis-genocide), 4 tracks
- [x] [Faces of Oglogoth](https://thehighblood.bandcamp.com/album/faces-of-oglogoth), 10 tracks
- [x] [Jugglanoids From Outer Space​/​First Interdimensional Clown Chronicles Volume One [UNRELEASED COMPILATION]](https://thehighblood.bandcamp.com/album/jugglanoids-from-outer-space-first-interdimensional-clown-chronicles-volume-one-unreleased-compilation), 8 tracks

These generally have lyrics, obviously. We can't parse death metal vocals but maybe someone else can!?

**Comment by Niklink** [comment]
Addressed by #389
