### ISSUE TITLE
Album addition: Showtime (Svix Mix) + reference trouble

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#446]
> Add Showtime (Svix Mix), YAML for this is done by Lilith - just needs references updated as described here: https://discord.com/channels/749042497610842152/779895315750715422/1205587274516135936

> Edit 3/21: Also, confirm/fix-up reference trouble in [Showtime (Svix Mix)](https://hsmusic.wiki/preview-en/track/showtime-svix-mix/). We probably accidentally removed its reference to Showtime (Original Mix) while reviewing some changes from Lilith a while ago, as it might've been listed as a rerelease of a track that was eventually excluded from those changes.

Thanks, Lilith!

**Comment by towerofnix** [comment]
See: [#hsmusic-chat](https://discord.com/channels/749042497610842152/779895315750715422/1205543231392055317) (related to #416)
