### ISSUE TITLE
Flash addition: Keytar Fox

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#449]
> oh nuts I forgot about this (2012-01-23) (although I don't think it had a name at this point; however, Induction comes with not only Fin, but also Keytar Fox's SWF, but I guess I'll look inside with JPEXS ffdec and see if it has a name (nope, no name)) 

Thanks, Lilith!

YT link: https://www.youtube.com/watch?v=IjvyG8GyWBI

> Keystar Fox features Havoc. It's not really a fandom flash, but should be issuefied for note anyway

**Comment by towerofnix** [comment]
It's Trepidation actually, not Havoc. (Thanks to a YT commenter for saving our mutton. Pretty sure this is a mistake we made in passing over it, not Lilith.)
