### ISSUE TITLE
Reference investigation: Hopes and Dreams / SAVE the World / Last Goodbye

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#450]
> Hopes and Dreams and SAVE the World reference Penumbra Phantasm. Still need to investigate exact reference placement (i.e. position in each list, and should it be included in both lists or only Hopes and Dreams).

> assuming SAVE the World and Last Goodbye are based on Hopes and Dreams, StW and LG inherit the reference from Hopes and Dreams

> yeye, we mostly wanna make sure abt the other references in StW and Last Goodbye, should any of those ALSO be inherited from hopes and dreams or are they all new/usage original to StW/LG
(we havent actually reviewed these ref lists LMAO maybe they already don't have any overlap)

Original message:

> I've always been skeptical on the whole "Penumbra Phantasm is in Hopes and Dreams" thing, but the other day I accidentally isolated that piano part in SAVE the World and Last Goodbye (it's basically the same as in HaD), and now I'm starting to actually believe it was done intentionally lmao
> feels more intentional than THE HOLY
[saveee_PROCESSED.zip](https://github.com/hsmusic/hsmusic-data/files/14861682/saveee_PROCESSED.zip)

I still feel this requires more investigatin' personally.
Thanks, Morris!

**Comment by towerofnix** [comment]
Closing in favor of #514 which includes a couple links to more recent discussion.
