### ISSUE TITLE
Various improvements: Psycholonials

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#455]
- [Add official YouTube listening links](https://www.youtube.com/playlist?list=OLAK5uy_lTL6fk9GCYnvxc37bE4M2NXURZuPl-N5U)
- Add commentary note about EP removal
- Add alternate album art
- Add additional name (Psycholonials (Original Game Soundtrack))

**Comment by Niklink** [comment]
Forgot that additional names for albums don't seem to be a thing rn. Will get added when it does and we do a pass for album names as a whole!

To make up for it we're adding missing HQ art across Psycholonials instead.

**Comment by towerofnix** [comment]
Thanks, we're tracking additional naems for albums in general in #439 — we've added an entry for Psycholonials there!
