### ISSUE TITLE
DCRC website listening links are broken

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#468]
The whole DCRC music website has been completely borked since [at least mid-February](https://github.com/AggressivelyMeows/Vast-Error-music-community/issues/8) so currently all https://music.deconreconstruction.com/ listening links are commented out. This issue will be resolved when either all these listening links are deleted entirely or the website issue is fixed and they can be reinstated to the wiki. If it is the latter a pass needs to be made since many Vast Error albums are missing per-track listening links anyways.

**Comment by towerofnix** [comment]
Let's give this til October LOL
