### ISSUE TITLE
Various improvements: Doctor's Descent

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#488]
Better quality cover and audio.
Thanks, Amiboost!

https://cdn.discordapp.com/attachments/935007764042874931/1229040749211943084/cover.png
https://cdn.discordapp.com/attachments/935007764042874931/1229040749387976784/Doctor_Descent.ogg

**Comment by towerofnix** [comment]
@Niklink best to link to messages directly, rather than attachments, which may expire or go inaccessible. ^^

[#issuefication-zone](https://discord.com/channels/749042497610842152/935007764042874931/1229040749773983855)

**Comment by towerofnix** [comment]
Ha ha, yes, the attachments did go inaccessible.
