### ISSUE TITLE
Bowman "Archive" reordering

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#5]
Transferred from notabug#13 - by @GiovanH, 9 Jan 2022:

---

The "archive" album has had two distinct states, with two different covers and track orderings:

https://web.archive.org/web/20170519092710/https://bowman.bandcamp.com/album/archive

https://bowman.bandcamp.com/album/archive

I propose these be considered two distinct albums and listed accordingly.

**Comment by Niklink** [comment]
> alright so the way he explained it was, he wanted to switch his name over from 'Michael Bowman' to 'Michael Guy Bowman' to match his homestuck credits, and that required basically reuploading every one of his albums, and when he did that with archive distrokid caught that the original cover art used licensed stock images and flagged it
> 
> so that's why the art was changed, and then while he was doing that he decided to switch up the track order and move some stuff to bonus tracks to 'make it more listenable' as a hypothetical physical release
> 
> felt that because archive was kind of a dump of bits and ends and not a cohesive album experience it wasn't a big deal to edit it in that way

I asked Bowman about it and this is my recollection of what he answered

**Comment by towerofnix** [comment]
Some renamed tracks - thanks to Lilith for noting these:

> Emery's Theme, formerly Crimesters Credits, and Emery's Theme (Fast Version), formerly Crimesters Theme ... Awake (2013 Version) was Awake

Looking to include the original release as a separate album, like Gio suggested originally. The generally distinct presentation (art, track list, description) make it more or less its own thing - best to have both versions represented fully.
