### ISSUE TITLE
"Milky Way Wishes (Shooting)" arrangement info

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#54]
FF's notes: arrangement of "Galactic Nova" from Kirby Super Star by Jun Ishikawa.

The only uploads of [Galactic Nova](https://www.youtube.com/watch?v=qAyN3ixzGQY) I could find were from Kirby Super Star Ultra (the DS remake). Uploads of the same song from the SNES original seem to go by [Heart of Nova](https://www.youtube.com/watch?v=w9tWq6FIwzA).

Will leave this up to people more knowledgeable than me in Kirby lore to decide whether the *referencing* track, [Vagrant Counting Song of Retrospection](https://www.youtube.com/watch?v=tK1_m7f1UhA), references anything unique in [Milky Way Wishes (Shooting)](https://www.youtube.com/watch?v=DuVGZdzEGF8) or more directly references the original Heart of Nova.

Also the wiki currently has the track as "Milky Way Wishes: Shooting", which should probably be changed to "(Shooting)" formatting.

Thanks, FF!

**Comment by Niklink** [comment]
> Vagrant Counting Song of Retrospection is for sure NOT referencing the in-between track from Rainbow Curse, the rhythm in question is directly originating from "Galactic Nova" (which through research the name is officially "Galactic Nova" on OST releases, just since those are few and far between + japan only for the most part came to be known by the in-game boss name instead)

> alright, i've already done the research the first time so let me attempt to elaborate: on certain re-releases of the Kirby Super Star ost(s) tracks would be formatted by the sub-game/story they appear in followed by the tracks name/whatever they decide to call certain tracks at that time i.e. Revenge of Meta Knight: Taking Over the Halberd, Revenge of Meta Knight: Grape Garden, Milky Way Wishes: Map. so Rainbow Curse is a cover of the track using that naming convention (certain nintendo games will use the exact same name for a cover of a track, you know how many Green Greens there are that are different?) and Counting Song is using the rhythm from the original track that also is used in Rainbow Curse due to being a cover. if you want the musical proof of this:
https://www.youtube.com/watch?v=X2VH8IxekEA Kirby Super Star (funnily enough, video's title shows this problem in full)
https://www.youtube.com/watch?v=DuVGZdzEGF8 Rainbow Curse
https://www.youtube.com/watch?v=tK1_m7f1UhA Planet Robobot (listen to the backing rhythm at ~1:40)

more context from FF
