### ISSUE TITLE
Add Hilary 'Pie' Troiano commentary + transcripts

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#63]
https://jaydeis.tumblr.com/post/19609363685/someone-sent-me-a-pm-asking-for-some-commentary

Celeste offered to transcribe this stuff!

**Comment by towerofnix** [comment]
Note: This commentary applies to these two tracks!

- [Ace of Trump](https://hsmusic.wiki/track/ace-of-trump/) (MC:DD)
- [Homefree](https://hsmusic.wiki/track/homefree/) (HS vol. 8)
