### ISSUE TITLE
Review referenced tracks for DELTARUNE Chapter 2 OST

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#7]
Transferred from notabug#46, 7 Mar 2022:

---

FF made a list a while ago which should be reviewed, and any missing references added! Message link: https://discord.com/channels/749042497610842152/779895315750715422/889296554052161538

**Comment by Niklink** [comment]
BIG SHOT is missing a reference to Dummy (at 1:47 and 2:17) (thanks, Sgeo!)

There are also missing lyrics in BIG SHOT, NOW'S YOUR CHANCE TO BE A, probably a couple other places.
