### ISSUE TITLE
Run an accessibility pass on all custom colors on the wiki

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#8]
Transferred from notabug#53, 17 Mar 2022:

---

There are a lot of custom colors on the wiki, which determine (most importantly) the color of associated link text (as well as general links on the colored thing's dedicated page). We should run a pass across all present colors to test for contrast against the (more or less) solid black background of wiki pages.

**Things with custom colors:**

- Album (and occasionally individual track groups)
- Group Category (e.g. "Solo Musicians", "Fan-Musician Groups")
- Art Tag
- Homepage Row
- Flash Act
- Wiki Info (i.e. the main primary color of the whole wiki)

Of these, albums and art tags are the main concern - the rest should already be pretty well suited for a black backdrop.

Yes, this includes choosing better (if non-canonical) colors than `#1313be` for [blue-bloods](https://hsmusic.wiki/tag/equius/).

**Comment by Niklink** [comment]
portalstuck is definitely a smidge too dark oops my bad

**Comment by towerofnix** [comment]
Done in commits 6ffede4a469d81081cf0ddc79552deef5f8793e3 and d9cad071dea78b66fa698b5a1e44c88cbc0007af!
