### ISSUE TITLE
Homepage official discography carousel should have albums manually selected

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-data#95]
Whoops, I don't know how I let this slip!

The homepage carousel is just Official Discography, so the albums should be basically the same, though we've got 2x5 instead of 2x6 here. Probably cut Genesis Frog (least recognizable solo album) and Vol. 1-2-3-4 (suits main Official carousel better). We can select different albums if anyone offers a counterpoint though.

Manual selection is just by replacing these lines in `homepage.yaml`...

```yaml
Group: group:official
Count: 10
```

...with these:

```yaml
Albums:
- # whatever albums desired go here
- ...
```

**Comment by Niklink** [comment]
Don't think Vol. 1-4 should be taken out it's like... core Homestuck Music.
Genesis Frog is fine to take out, I think. Sorry Alex.
As long as it's not Alterniabound or Hiveswap either, I don't think I super care which other album we obviate.
